swagger: '2.0'
info:
  title: Blockchain Event API
  version: '1.0'
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/event/register':
    post:
      operationId: Registration
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/EventRegistrationRequest'
definitions:
  EventRegistrationRequest:
    type: object
    properties:
      contract:
        type: object
        properties:
          name: 
            type: string
      event:
        type: object
        properties:
          name: 
            type: string
          abi: 
            type: object
  EventRegistrationResponse:
    type: object
    required: 
      - contract
    properties:
      contract:
        type: string
